dist: xenial
sudo: false
language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements-dev.txt -U
  - pip install -e .

script:
  - flake8 pydantic_collections tests
  - pytest --cov=./pydantic_collections tests/ -s
#  - pytest --cov=./pydantic_collections tests/ --cov-report term-missing -s

after_success:
  - coveralls

cache: false

notifications:
  email: false
